set number
set relativenumber
set cursorline
syntax on
filetype plugin indent on
filetype on
set re=0
set mouse=a
set wildmenu
set autoread
set history=500
set so=7
set cmdheight=1
set hid
set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch
set mat=2
set noerrorbells
set novisualbell
set t_vb=
set tm=500
set nobackup
set nowb
set noswapfile
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set laststatus=2
set ruler

set termguicolors
let g:everforest_background = 'medium'
let g:everforest_better_performance = 1
colorscheme everforest
set background=dark

set path+=**
set wildignore+=*/node_modules/*
set wildignore+=*/dist/*
set completeopt+=longest,menuone,noselect,popup
let g:netrw_banner = 0

let mapleader=" "
map <leader>l :bnext<cr>
map <leader>h :bprevious<cr>
map <leader>d :bdelete<cr>
map - :e .<cr>
map <leader><leader> :find 
