set nocompatible

let mapleader=" "
let maplocalleader=" "

syntax on
filetype plugin indent on
filetype on
set re=0

set number
set relativenumber
set cursorline
set encoding=UTF-8
set mouse=a
set wildmenu
set autoindent
set autoread
set history=500
set so=7
set cmdheight=1
set hid

set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch

set noerrorbells
set novisualbell
set nobackup
set nowb
set noswapfile

set splitright
set splitbelow
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set laststatus=2
set ruler

set termguicolors
let g:everforest_background = 'medium'
let g:everforest_better_performance = 1
set background=dark
colorscheme everforest
"hi Normal guibg=NONE ctermbg=NONE
"hi NonText guibg=NONE ctermbg=NONE

set path+=**
set wildignore+=*/node_modules/*
set wildignore+=*/dist/*
set completeopt+=longest,menuone,noselect,popup
let g:netrw_banner = 0

nnoremap [b :bnext<cr>
nnoremap ]b :bprevious<cr>
nnoremap - :e .<cr>
nnoremap <leader><leader> :find 
nnoremap <esc> :set nohlsearch<cr>
