set number
set relativenumber
set cursorline
syntax on
filetype plugin indent on
set re=0
set mouse=a
colorscheme habamax
set wildmenu
set autoread
set history=500
set background=dark
set so=7
set ruler
set cmdheight=1
set hid
set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch
set mat=2
set noerrorbells
set novisualbell
set t_vb=
set tm=500
set nobackup
set nowb
set noswapfile
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set laststatus=2

set path+=**
set wildignore+=*/node_modules/*
set wildignore+=*/dist/*
set statusline=%f         " Path to the file_
set statusline+=\ -\      " Separator
set statusline+=%y        " Filetype of the file
set completeopt+=longest,menuone,noselect
let g:netrw_banner = 0

let mapleader=" "
map <leader>l :bnext<cr>
map <leader>h :bprevious<cr>
map <leader>d :bdelete<cr>
map - :e .<cr>
map <leader><leader> :find 
