set nocompatible

let mapleader=" "
let maplocalleader=" "

syntax on
filetype plugin indent on
filetype on
set re=0

set number
set relativenumber
set cursorline
set encoding=UTF-8
set mouse=a
set wildmenu
set autoindent
set autoread
set history=500
set so=7
set cmdheight=1
set hid

set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch

set noerrorbells
set novisualbell
set nobackup
set nowb
set noswapfile

set splitright
set splitbelow
set expandtab
set smarttab
set shiftwidth=2
set tabstop=2
set laststatus=2
set ruler

set termguicolors
colorscheme habamax
hi Normal guibg=NONE ctermbg=NONE

set path+=**
set wildignore+=*/node_modules/*
set wildignore+=*/dist/*
set completeopt+=longest,menuone,noselect,popup
let g:netrw_banner = 0

packadd! comment
packadd! matchit

augroup highlight_yank
  autocmd!
  autocmd TextYankPost * call FlashYankedText()
augroup END

function! FlashYankedText()
  if v:event.operator ==# 'y'
    let l:yank_match = matchadd('IncSearch','\v%''\[\_.*%''\]')
    defer timer_start(200, {-> matchdelete(l:yank_match)})
  endif
endfunction


nnoremap [b :bnext<cr>
nnoremap ]b :bprevious<cr>
nnoremap - :e .<cr>
nnoremap <leader><leader> :find 
nnoremap <esc> :set nohlsearch<cr>
