# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol   = "[➜](bold red)" 
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = false

[username]
style_user = "bold  blue dimmed"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = true
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = false

[java]
disabled = true

[scala]
format = "via [$symbol](red)[$version]($style)"
style = "red dimmed"
disabled = true

[golang]
format = "via [$symbol](cyan dimmed)[$version](cyan dimmed)" 
symbol = "ʕ◔ϖ◔ʔ"
disabled = true


[nodejs]
format = 'via [$symbol($version )]($style)'
disabled = true


[helm]
disabled = false
style = "yellow dimmed"
detect_folders = ["helm-charts"]

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "on [$symbol$branch]($style)"
style = "bold green"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "👊"
ahead = "🏎️ 💨×${count}"
behind = "🐢 ×${count}"
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "🛤️  ×${count}"
stashed = "📦"
modified = "📝 ×${count}"
staged = "🗃️  ×${coun}"
renamed = "📛 ×${count}"
deleted = "🗑️  ×${coun}"
style = "bright white"
format = "$all_status$ahead_behind "

[gcloud]
format = 'on [$symbol$project(\($region\))]($style)'
disabled = true

[aws]
format = 'on [$symbol $profile | $region \[$duration\]]($style)'


[kubernetes]
symbol = "☸ "
disabled = true
style = "bold blue"


